/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nppmgfxwdybrigxsffjs"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wcG1nZnh3ZHlicmlneHNmZmpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxNjI3MTQsImV4cCI6MjA3NTczODcxNH0.Fe6uvQ_NT5N2-jKre4_GwMFnB3q09bMGaY-NyneDoY8"